<script setup>
import { Head, Link, useForm } from '@inertiajs/vue3'
import AppShell from '../../Layouts/AppShell.vue'
defineOptions({ layout: AppShell })
defineProps({ jobs: Object })
const form = useForm({ file: null, strategy: 'atomic' })
const submit = () => form.post('/imports/assets/preview', { forceFormData: true })
</script>
<template><Head title="Impor Data" /><main class="mx-auto max-w-7xl space-y-8 px-4 py-8 sm:px-6 lg:py-10">
<header class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-blue-700">Migrasi Data</p><h1 class="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Impor data aset</h1><p class="mt-2 max-w-2xl text-slate-600">Bawa data Excel lama ke DESATARA dengan validasi sebelum masuk register aset.</p></div><a href="/imports/template" class="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold shadow-sm hover:bg-slate-50">Unduh template CSV</a></header>
<section class="grid gap-4 md:grid-cols-3"><article v-for="[n,title,text] in [['1','Pilih file','Gunakan CSV atau XLSX dari data aset desa.'],['2','Periksa hasil','DESATARA menandai data valid, duplikat, dan bermasalah.'],['3','Konfirmasi impor','Data baru masuk register setelah Anda menyetujuinya.']]" :key="n" class="rounded-xl border border-slate-200 bg-white p-4"><span class="inline-flex h-7 w-7 items-center justify-center rounded-full bg-blue-50 text-sm font-bold text-blue-800">{{ n }}</span><h2 class="mt-3 font-bold">{{ title }}</h2><p class="mt-1 text-sm leading-6 text-slate-500">{{ text }}</p></article></section>
<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><form class="space-y-5" @submit.prevent="submit"><div><label class="text-sm font-bold" for="asset-import-file">File aset</label><div class="mt-2 rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-5"><input id="asset-import-file" type="file" accept=".csv,.xlsx,.xls" required class="block w-full text-sm file:mr-4 file:rounded-lg file:border-0 file:bg-[#0B2E5B] file:px-4 file:py-2.5 file:font-semibold file:text-white" @change="form.file = $event.target.files[0]"><p class="mt-3 text-xs leading-5 text-slate-500">CSV atau XLSX Â· maksimal 10 MB Â· maksimal 5.000 baris. File XLS lama perlu disimpan ulang sebagai XLSX.</p></div><p v-if="form.errors.file" class="mt-2 text-sm font-medium text-red-700">{{ form.errors.file }}</p></div>
<div class="grid gap-4 md:grid-cols-[1fr_auto] md:items-end"><fieldset><legend class="text-sm font-bold">Jika ada baris bermasalah</legend><div class="mt-2 grid gap-2 sm:grid-cols-2"><label :class="[form.strategy === 'atomic' ? 'border-blue-600 bg-blue-50' : 'border-slate-200', 'cursor-pointer rounded-xl border p-3']"><input v-model="form.strategy" type="radio" value="atomic" class="mr-2"> <span class="font-semibold">Hentikan seluruh impor</span><p class="ml-6 mt-1 text-xs text-slate-500">Paling aman untuk migrasi awal.</p></label><label :class="[form.strategy === 'partial' ? 'border-blue-600 bg-blue-50' : 'border-slate-200', 'cursor-pointer rounded-xl border p-3']"><input v-model="form.strategy" type="radio" value="partial" class="mr-2"> <span class="font-semibold">Impor yang valid saja</span><p class="ml-6 mt-1 text-xs text-slate-500">Baris bermasalah tetap ditahan.</p></label></div></fieldset><button :disabled="form.processing" class="rounded-lg bg-[#0B2E5B] px-5 py-3 text-sm font-bold text-white shadow-sm disabled:opacity-50">{{ form.processing ? 'Memeriksa file...' : 'Periksa & Preview' }}</button></div></form></section>
<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold">Riwayat impor</h2><p class="mt-1 text-sm text-slate-500">Lacak preview dan hasil migrasi data sebelumnya.</p></div><div v-if="jobs?.data?.length" class="divide-y divide-slate-100"><Link v-for="job in jobs.data" :key="job.uuid" :href="`/imports/${job.uuid}`" class="flex flex-wrap items-center justify-between gap-3 px-5 py-4 hover:bg-slate-50"><div><strong>Impor aset</strong><p class="mt-1 text-sm text-slate-500">{{ new Date(job.created_at).toLocaleString('id-ID') }} Â· {{ job.total_rows }} baris</p></div><div class="text-right text-sm"><span class="rounded-full bg-slate-100 px-2.5 py-1 font-semibold">{{ job.status }}</span><p class="mt-2 text-xs text-slate-500">{{ job.valid_rows }} valid Â· {{ job.invalid_rows }} bermasalah</p></div></Link></div><div v-else class="px-5 py-10 text-center"><p class="font-semibold text-slate-700">Belum ada riwayat impor</p><p class="mt-1 text-sm text-slate-500">Impor pertama Anda akan tercatat di sini.</p></div></section>
</main></template>