<script setup>
import { Head, Link, useForm, usePage } from '@inertiajs/vue3'
import AppShell from '../../Layouts/AppShell.vue'

defineOptions({ layout: AppShell })
const props = defineProps({ title: String, description: String, surface: String, kind: String, items: Object, createUrl: String, assets: Array, periods: Array, templates: Array, roles: Array, inventoryItems: Array, discrepancies: Array, errors: Array, approval: Object })
const page = usePage()
const can = (permission) => page.props.permissions?.[permission] === true
const form = useForm({ name: '', period_label: '', reference_at: new Date().toISOString().slice(0, 10), code: '', location_type: 'room', type: 'unit', asset_id: '', asset_ids: [], maintenance_type: '', mutation_type: 'relocation', destination_location_id: '', effective_at: new Date().toISOString().slice(0, 10), reason: '', period_year: new Date().getFullYear(), year: new Date().getFullYear(), period_type: 'year', start_date: new Date().toISOString().slice(0, 10), end_date: new Date().toISOString().slice(0, 10), target_system: 'internal-boundary', rows: '[{"name":"Contoh aset","classification_id":1}]', strategy: 'atomic', action: '', idempotency_key: crypto.randomUUID(), notes: '', period_id: '', template_version_id: '' })
const post = (url, data = form) => data.post(url, { preserveScroll: true })
const rows = () => { try { return JSON.parse(form.rows) } catch { return [] } }
</script>

<template>
  <Head :title="title" />
  <main class="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6">
    <header><p class="text-sm font-semibold uppercase tracking-wide text-blue-700">DESATARA Ã‚Â· {{ $page.props.tenantContext?.name }}</p><h1 class="mt-2 text-3xl font-semibold">{{ title }}</h1><p class="mt-2 text-slate-600">{{ description }}</p></header>

    <section v-if="surface === 'assets'" class="space-y-4">
      <form method="get" class="flex flex-wrap gap-2"><input name="q" aria-label="Cari aset" class="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2" placeholder="Nama, kode, atau register"><button class="rounded-lg bg-blue-800 px-4 py-2 font-semibold text-white">Cari</button><Link v-if="can('assets.create')" href="/assets/create" class="rounded-lg border border-slate-300 px-4 py-2">Tambah aset</Link></form>
      <section class="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table class="w-full text-left text-sm"><thead class="bg-slate-50"><tr><th class="p-3">Aset</th><th class="p-3">Klasifikasi</th><th class="p-3">Kondisi</th><th class="p-3">Lifecycle</th></tr></thead><tbody><tr v-for="item in items?.data" :key="item.uuid" class="border-t border-slate-100"><td class="p-3"><Link :href="`/assets/${item.uuid}`" class="font-medium text-blue-700">{{ item.name }}</Link><div class="text-xs text-slate-500">{{ item.asset_code || 'Tanpa kode' }} Ã‚Â· {{ item.register_number || 'Tanpa register' }}</div></td><td class="p-3">{{ item.classification?.name || '-' }}</td><td class="p-3">{{ item.condition }}</td><td class="p-3">{{ item.lifecycle_status }}</td></tr></tbody></table><p v-if="!items?.data?.length" class="p-8 text-slate-500">Belum ada aset pada tenant aktif.</p></section>
    </section>

    <section v-else-if="surface === 'master-data'" class="space-y-4"><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><article v-for="item in items?.data" :key="item.id" class="rounded-xl border border-slate-200 bg-white p-4"><p class="text-xs text-slate-500">{{ item.code || item.party_type || item.id }}</p><h2 class="font-medium">{{ item.name || item.type || 'Penanggung jawab' }}</h2><p class="text-sm text-slate-500">{{ item.status }}</p></article></div><form v-if="kind !== 'classifications'" class="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-4" @submit.prevent="post(`/master-data/${kind}`)"><input v-model="form.code" v-if="kind !== 'responsible-parties'" required class="rounded-lg border border-slate-300 px-3 py-2" placeholder="Kode"><input v-model="form.name" v-if="kind !== 'responsible-parties'" required class="rounded-lg border border-slate-300 px-3 py-2" placeholder="Nama"><input v-model="form.location_type" v-if="kind === 'locations'" required class="rounded-lg border border-slate-300 px-3 py-2" placeholder="Tipe lokasi"><input v-model="form.type" v-if="kind === 'organizational-units'" required class="rounded-lg border border-slate-300 px-3 py-2" placeholder="Tipe unit"><button class="rounded-lg bg-blue-800 px-4 py-2 font-semibold text-white">Simpan</button></form></section>

    <section v-else-if="surface === 'inventory'" class="space-y-4"><form class="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-3" @submit.prevent="post('/inventory')"><input v-model="form.name" name="name" required class="rounded-lg border border-slate-300 px-3 py-2" placeholder="Nama sesi"><input v-model="form.period_label" required class="rounded-lg border border-slate-300 px-3 py-2" placeholder="Periode"><input v-model="form.reference_at" required type="date" class="rounded-lg border border-slate-300 px-3 py-2"><button class="rounded-lg bg-blue-800 px-4 py-2 font-semibold text-white">Buat sesi</button></form><section class="divide-y rounded-xl border border-slate-200 bg-white"><article v-for="item in items?.data" :key="item.uuid" class="flex flex-wrap items-center justify-between gap-3 p-4"><div><strong>{{ item.name }}</strong><p class="text-sm text-slate-500">{{ item.period_label }} Ã‚Â· {{ item.status }}</p></div><div class="flex gap-2"><form @submit.prevent="post(`/inventory/${item.uuid}/freeze`)"><button class="rounded border px-3 py-1 text-sm">Siapkan snapshot</button></form><form @submit.prevent="post(`/inventory/${item.uuid}/finalize`)"><button class="rounded border px-3 py-1 text-sm">Finalisasi</button></form></div></article></section><section v-if="inventoryItems?.length" class="rounded-xl border border-slate-200 bg-white p-4"><h2 class="font-semibold">Observasi item</h2><div v-for="item in inventoryItems" :key="item.id" class="mt-3 flex flex-wrap items-center justify-between gap-3 border-t pt-3"><span class="text-sm">{{ item.asset_name_snapshot }} Ã‚Â· {{ item.verification_result }}</span><form class="flex gap-2" @submit.prevent="post(`/inventory/items/${item.id}/observe`, Object.assign(form, { result: 'matched' }))"><button class="rounded border px-3 py-1 text-sm">Tandai cocok</button></form></div></section><section v-if="discrepancies?.length" class="rounded-xl border border-amber-200 bg-amber-50 p-4"><h2 class="font-semibold text-amber-900">Discrepancy terbuka</h2><div v-for="item in discrepancies" :key="item.id" class="mt-3 flex flex-wrap items-center justify-between gap-3 border-t border-amber-200 pt-3"><span class="text-sm text-amber-900">{{ item.discrepancy_type }} Ã‚Â· {{ item.description }}</span><form @submit.prevent="post(`/inventory/discrepancies/${item.id}/reconcile`, Object.assign(form, { resolution_type: 'no_change', idempotency_key: crypto.randomUUID() }))"><button class="rounded border border-amber-300 px-3 py-1 text-sm">Rekonsiliasi</button></form></div></section></section>

    <section v-else-if="surface === 'lifecycle'" class="space-y-4"><form class="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-4" @submit.prevent="post(`/lifecycle/${kind}`)"><select v-model="form.asset_id" v-if="!['transfers','disposals','usage'].includes(kind)" required class="rounded-lg border border-slate-300 px-3 py-2"><option value="">Pilih aset</option><option v-for="asset in assets" :key="asset.id" :value="asset.id">{{ asset.name }} ({{ asset.asset_code || '-' }})</option></select><input v-model="form.maintenance_type" v-if="kind === 'maintenance'" required class="rounded-lg border border-slate-300 px-3 py-2" placeholder="Jenis pemeliharaan"><input v-model="form.period_year" v-if="kind === 'usage'" type="number" required class="rounded-lg border border-slate-300 px-3 py-2" placeholder="Tahun"><input v-model="form.reason" v-if="['disposals','transfers'].includes(kind)" required class="rounded-lg border border-slate-300 px-3 py-2" placeholder="Alasan"><button class="rounded-lg bg-blue-800 px-4 py-2 font-semibold text-white">Catat operasi</button></form><section class="divide-y rounded-xl border border-slate-200 bg-white"><article v-for="item in items?.data" :key="item.id" class="flex items-center justify-between gap-3 p-4"><div><strong>{{ item.name || item.maintenance_type || item.transfer_type || item.disposal_type || item.purpose || item.utilization_type || item.safeguard_category }}</strong><p class="text-sm text-slate-500">{{ item.status || item.effective_at || item.created_at }}</p></div><form v-if="['maintenance','transfers','disposals','usage'].includes(kind)" @submit.prevent="post(`/lifecycle/${kind}/${item.id}/execute`)"><button class="rounded border px-3 py-1 text-sm">Jalankan transisi</button></form></article></section></section>

    <section v-else-if="surface === 'approvals'" class="divide-y rounded-xl border border-slate-200 bg-white"><article v-for="item in items?.data" :key="item.id" class="flex flex-wrap items-center justify-between gap-3 p-4"><div><Link :href="`/approvals/${item.id}`" class="font-medium text-blue-700">Permohonan #{{ item.id }}</Link><p class="text-sm text-slate-500">{{ item.status }} Ã‚Â· {{ item.submitted_at }}</p></div><div class="flex gap-2"><form @submit.prevent="post(`/approvals/${item.id}/action`, Object.assign(form, { action: 'approve', idempotency_key: crypto.randomUUID() }))"><button class="rounded bg-blue-800 px-3 py-1 text-sm text-white">Setujui</button></form><form @submit.prevent="post(`/approvals/${item.id}/action`, Object.assign(form, { action: 'reject', idempotency_key: crypto.randomUUID() }))"><button class="rounded border px-3 py-1 text-sm">Tolak</button></form></div></article></section>

    <section v-else-if="surface === 'approval-detail'" class="space-y-4"><Link href="/approvals" class="text-sm font-medium text-blue-700">Ã¢â€ Â Inbox persetujuan</Link><section class="rounded-xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Status request</p><p class="mt-1 text-xl font-semibold">{{ approval.status }}</p><h2 class="mt-5 font-semibold">Workflow timeline</h2><ol class="mt-3 space-y-2"><li v-for="step in approval.steps" :key="step.id" class="rounded bg-slate-50 p-3 text-sm">Tahap {{ step.sequence }} Ã‚Â· {{ step.status }}<span v-if="step.required_permission" class="text-slate-500"> Ã‚Â· {{ step.required_permission.code }}</span></li></ol><div v-if="approval.status === 'pending'" class="mt-5 flex gap-2"><form @submit.prevent="post(`/approvals/${approval.id}/action`, Object.assign(form, { action: 'approve', idempotency_key: crypto.randomUUID() }))"><button class="rounded bg-blue-800 px-4 py-2 text-white">Setujui</button></form><form @submit.prevent="post(`/approvals/${approval.id}/action`, Object.assign(form, { action: 'reject', idempotency_key: crypto.randomUUID() }))"><button class="rounded border px-4 py-2">Tolak</button></form></div></section></section>

    <section v-else-if="surface === 'reports'" class="space-y-4"><form class="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-4" @submit.prevent="post('/reports/periods')"><input v-model="form.year" type="number" required class="rounded-lg border border-slate-300 px-3 py-2" placeholder="Tahun"><select v-model="form.period_type" required class="rounded-lg border border-slate-300 px-3 py-2"><option value="year">Tahun</option><option value="semester">Semester</option></select><input v-model="form.start_date" type="date" required class="rounded-lg border border-slate-300 px-3 py-2"><input v-model="form.end_date" type="date" required class="rounded-lg border border-slate-300 px-3 py-2"><button class="rounded-lg bg-blue-800 px-4 py-2 text-white">Buat periode</button></form><section class="divide-y rounded-xl border border-slate-200 bg-white"><article v-for="item in items?.data" :key="item.id" class="flex flex-wrap items-center justify-between gap-3 p-4"><div><strong>Report #{{ item.id }}</strong><p class="text-sm text-slate-500">{{ item.status }} Ã‚Â· Revisi {{ item.revision_number }}</p></div><div class="flex gap-2"><form v-if="item.status === 'draft'" @submit.prevent="post(`/reports/${item.id}/review`)"><button class="rounded border px-3 py-1 text-sm">Review</button></form><form v-if="item.status === 'review'" @submit.prevent="post(`/reports/${item.id}/finalize`)"><button class="rounded bg-blue-800 px-3 py-1 text-sm text-white">Finalisasi</button></form><Link v-if="item.status === 'finalized'" :href="`/reports/${item.id}/export`" class="rounded border px-3 py-1 text-sm">Export</Link></div></article></section></section>

    <section v-else-if="surface === 'interoperability'" class="space-y-4"><form class="space-y-3 rounded-xl border border-slate-200 bg-white p-4" @submit.prevent="post('/interoperability/import/preview', Object.assign(form, { rows: rows() }))"><label class="block text-sm font-medium">Rows JSON untuk preview</label><textarea v-model="form.rows" rows="5" class="w-full rounded-lg border border-slate-300 p-3"></textarea><select v-model="form.strategy" class="rounded-lg border border-slate-300 px-3 py-2"><option value="atomic">Atomic</option><option value="partial">Partial</option></select><button class="rounded-lg bg-blue-800 px-4 py-2 text-white">Preview import</button></form><form class="flex flex-wrap gap-2 rounded-xl border border-slate-200 bg-white p-4" @submit.prevent="post(`/interoperability/import/${form.template_version_id}/commit`)"><input v-model="form.template_version_id" required class="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2" placeholder="UUID import preview"><button class="rounded-lg border px-4 py-2">Commit import</button></form><form @submit.prevent="post('/interoperability/export')"><input v-model="form.target_system" class="rounded-lg border border-slate-300 px-3 py-2"><button class="ml-2 rounded-lg border px-4 py-2">Export tenant</button></form><section class="divide-y rounded-xl border border-slate-200 bg-white"><article v-for="item in items?.data" :key="item.id || item.uuid" class="p-4"><strong>{{ item.status }}</strong><p class="text-sm text-slate-500">{{ item.uuid || item.id }} Ã‚Â· {{ item.total_rows || '' }}</p></article></section><section v-if="errors?.length" class="rounded-xl border border-red-200 bg-red-50 p-4"><h2 class="font-semibold text-red-900">Error import</h2><p v-for="error in errors" :key="error.id" class="mt-2 text-sm text-red-800">Baris {{ error.import_row_id }} Ã‚Â· {{ error.field_name }} Ã‚Â· {{ error.message }}</p></section></section>

    <section v-else-if="surface === 'administration'" class="space-y-4"><section class="divide-y rounded-xl border border-slate-200 bg-white"><article v-for="item in items?.data" :key="item.id" class="p-4"><strong>{{ item.user?.name || item.action || item.code || 'Pengaturan tenant' }}</strong><p class="text-sm text-slate-500">{{ item.user?.email || item.occurred_at || item.name || '' }}</p></article></section><form v-if="kind === 'members'" class="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-3" @submit.prevent="post('/administration/memberships')"><input v-model="form.email" type="email" required class="rounded-lg border border-slate-300 px-3 py-2" placeholder="Email user yang sudah ada"><select v-model="form.role_id" required class="rounded-lg border border-slate-300 px-3 py-2"><option v-for="role in roles" :key="role.id" :value="role.id">{{ role.name }}</option></select><button class="rounded-lg bg-blue-800 px-4 py-2 text-white">Tambahkan membership</button></form></section>

    <p v-if="!items?.data?.length && !['assets','master-data','inventory','lifecycle','approvals','reports','interoperability','administration'].includes(surface)" class="rounded-xl border bg-white p-8 text-slate-500">Belum ada data pada tenant aktif.</p>
  </main>
</template>
